using LegalOfficeManagerApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace LegalOfficeManagerApp.Data
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>  // 01:46:42
    {
        //constructor 

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }

        //DbSet for the LegalOfficeEntry model
        public DbSet<LegalOfficeEntry> LegalOfficeEntries { get; set; }


        //generated by OnModelCreating method
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);



            //adding data to the LegalOfficeEntry table
            modelBuilder.Entity<LegalOfficeEntry>().HasData(
            new LegalOfficeEntry
            {
                Id = 1,
                Name = "John",
                Surname = "Doe",
                Email = "john.doe@example.com",
                Phone = "+48 600 700 800",
                Address = "ul. Przykladowa 12/4",
                City = "Warszawa",
                PostalCode = "00-001",
                Country = "Polska",
                CaseType = "Sprawa cywilna",
                Notes = "Klient zadzwonil w sprawie rozwodu. Termin spotkania ustalony.",
                Status = "W toku",
                CreatedAt = new DateTime(2024, 5, 1),
                UpdatedAt = new DateTime(2024, 5, 1)
            },
            new LegalOfficeEntry
            {
                Id = 2,
                Name = "Anna",
                Surname = "Smith",
                Email = "anna.smith@example.com",
                Phone = "+48 501 123 456",
                Address = "Green Avenue 45",
                City = "Krakow",
                PostalCode = "30-001",
                Country = "Poland",
                CaseType = "Criminal Defense",
                Notes = "Case related to traffic violation.",
                Status = "Pending",
                CreatedAt = new DateTime(2024, 4, 29),
                UpdatedAt = new DateTime(2024, 5, 1)
            },
            new LegalOfficeEntry
            {
                Id = 3,
                Name = "Michael",
                Surname = "Brown",
                Email = "michael.brown@example.com",
                Phone = "+48 503 987 654",
                Address = "Main Street 10",
                City = "Gdansk",
                PostalCode = "80-001",
                Country = "Poland",
                CaseType = "Labor Law",
                Notes = "Client was dismissed from work. Initial consultation done.",
                Status = "In Progress",
                CreatedAt = new DateTime(2024, 4, 26),
                UpdatedAt = new DateTime(2024, 5, 1)
            },
            new LegalOfficeEntry
            {
                Id = 4,
                Name = "Emily",
                Surname = "Taylor",
                Email = "emily.taylor@example.com",
                Phone = "+48 502 222 333",
                Address = "Sunset Boulevard 9",
                City = "Lodz",
                PostalCode = "90-001",
                Country = "Poland",
                CaseType = "Family Law",
                Notes = "Divorce and custody issues.",
                Status = "Open",
                CreatedAt = new DateTime(2024, 4, 21),
                UpdatedAt = new DateTime(2024, 4, 30)
            },
            new LegalOfficeEntry
            {
                Id = 5,
                Name = "Robert",
                Surname = "Johnson",
                Email = "robert.johnson@example.com",
                Phone = "+48 509 444 555",
                Address = "River Street 33",
                City = "Poznan",
                PostalCode = "60-001",
                Country = "Poland",
                CaseType = "Property Dispute",
                Notes = "Client in conflict with neighbor over land border.",
                Status = "Closed",
                CreatedAt = new DateTime(2024, 4, 1),
                UpdatedAt = new DateTime(2024, 4, 28)
            },
            new LegalOfficeEntry
            {
                Id = 6,
                Name = "Laura",
                Surname = "White",
                Email = "laura.white@example.com",
                Phone = "+48 508 888 111",
                Address = "Ocean Drive 11",
                City = "Szczecin",
                PostalCode = "70-001",
                Country = "Poland",
                CaseType = "Sprawa karna",
                Notes = "Postepowanie w sprawie kradziezy.",
                Status = "Pending",
                CreatedAt = new DateTime(2024, 4, 15),
                UpdatedAt = new DateTime(2024, 4, 25)
            },
            new LegalOfficeEntry
            {
                Id = 7,
                Name = "Daniel",
                Surname = "Evans",
                Email = "daniel.evans@example.com",
                Phone = "+48 507 111 222",
                Address = "Hill Street 5",
                City = "Lublin",
                PostalCode = "20-001",
                Country = "Poland",
                CaseType = "Prawo pracy",
                Notes = "Brak zaplaty za nadgodziny.",
                Status = "W toku",
                CreatedAt = new DateTime(2024, 4, 18),
                UpdatedAt = new DateTime(2024, 4, 27)
            },
            new LegalOfficeEntry
            {
                Id = 8,
                Name = "Olivia",
                Surname = "Clark",
                Email = "olivia.clark@example.com",
                Phone = "+48 506 333 444",
                Address = "Lake Street 7",
                City = "Katowice",
                PostalCode = "40-001",
                Country = "Poland",
                CaseType = "Spadkowe",
                Notes = "Podzial majatku po zmarlym ojcu.",
                Status = "W toku",
                CreatedAt = new DateTime(2024, 3, 30),
                UpdatedAt = new DateTime(2024, 4, 20)
            },
            new LegalOfficeEntry
            {
                Id = 9,
                Name = "Tom",
                Surname = "Anderson",
                Email = "tom.anderson@example.com",
                Phone = "+48 505 777 666",
                Address = "Forest Road 2",
                City = "Rzeszow",
                PostalCode = "35-001",
                Country = "Poland",
                CaseType = "Prawo cywilne",
                Notes = "Spor o umowe najmu.",
                Status = "W toku",
                CreatedAt = new DateTime(2024, 4, 5),
                UpdatedAt = new DateTime(2024, 4, 19)
            },
            new LegalOfficeEntry
            {
                Id = 10,
                Name = "Natalie",
                Surname = "Adams",
                Email = "natalie.adams@example.com",
                Phone = "+48 504 999 333",
                Address = "Winter Lane 12",
                City = "Bydgoszcz",
                PostalCode = "85-001",
                Country = "Poland",
                CaseType = "Prawo rodzinne",
                Notes = "Alimenty i opieka nad dzieckiem.",
                Status = "Open",
                CreatedAt = new DateTime(2024, 4, 3),
                UpdatedAt = new DateTime(2024, 4, 17)
            },
            new LegalOfficeEntry
            {
                Id = 11,
                Name = "Liam",
                Surname = "Baker",
                Email = "liam.baker@example.com",
                Phone = "+48 503 222 111",
                Address = "Bridge Street 19",
                City = "Torun",
                PostalCode = "87-100",
                Country = "Poland",
                CaseType = "Obrona karna",
                Notes = "Sprawa o pobicie.",
                Status = "Pending",
                CreatedAt = new DateTime(2024, 4, 10),
                UpdatedAt = new DateTime(2024, 4, 18)
            },
            new LegalOfficeEntry
            {
                Id = 12,
                Name = "Sophie",
                Surname = "Martin",
                Email = "sophie.martin@example.com",
                Phone = "+48 502 444 666",
                Address = "Oak Avenue 22",
                City = "Olsztyn",
                PostalCode = "10-001",
                Country = "Poland",
                CaseType = "Rozwod",
                Notes = "Klientka chce zakonczyc malzenstwo bez orzekania o winie.",
                Status = "Open",
                CreatedAt = new DateTime(2024, 4, 8),
                UpdatedAt = new DateTime(2024, 4, 16)
            },
            new LegalOfficeEntry
            {
                Id = 13,
                Name = "Adam",
                Surname = "Wright",
                Email = "adam.wright@example.com",
                Phone = "+48 501 111 555",
                Address = "Meadow Road 3",
                City = "Kielce",
                PostalCode = "25-001",
                Country = "Poland",
                CaseType = "Spor sasiedzki",
                Notes = "Halasujace psy sasiadow.",
                Status = "W toku",
                CreatedAt = new DateTime(2024, 4, 7),
                UpdatedAt = new DateTime(2024, 4, 15)
            },
            new LegalOfficeEntry
            {
                Id = 14,
                Name = "Grace",
                Surname = "Scott",
                Email = "grace.scott@example.com",
                Phone = "+48 509 123 777",
                Address = "Willow Street 8",
                City = "Bialystok",
                PostalCode = "15-001",
                Country = "Poland",
                CaseType = "Prawo spoek",
                Notes = "Zalozenie spoeki z o.o.",
                Status = "Pending",
                CreatedAt = new DateTime(2024, 4, 2),
                UpdatedAt = new DateTime(2024, 4, 12)
            },
            new LegalOfficeEntry
            {
                Id = 15,
                Name = "David",
                Surname = "Turner",
                Email = "david.turner@example.com",
                Phone = "+48 508 333 999",
                Address = "Maple Street 17",
                City = "Zielona Gora",
                PostalCode = "65-001",
                Country = "Poland",
                CaseType = "Prawo handlowe",
                Notes = "Spor z kontrahentem o niezaplacona fakture.",
                Status = "W toku",
                CreatedAt = new DateTime(2024, 3, 28),
                UpdatedAt = new DateTime(2024, 4, 10)
            }

        );
        
    
        }


    }


}
